### ISSUE TITLE
Variable case modifiers

### ISSUE THREAD

**Issue by willdady** [sdinesh86/template-generator#11]
It would be great if it was possible to declaratively define a variable's output case. For example e.g. `[{[myvariable|uppercase]}]`, `[{[myvariable|lowercase]}]`, `[{[myvariable|camelcase]}]` etc.

**Comment by sdinesh86** [comment]
hello @willdady 

I am bit stuck with some personal work, due to which I am not able to complete this feature I will try to see if i can complete it
