### ISSUE TITLE
When change case is used it's treated as a different variable

### ISSUE THREAD

**Issue by Aaron-Pool** [sdinesh86/template-generator#13]
If I use both `[{[ComponentName]}]` and `[{[ComponentName | camelCase]}]` in my code, it prompts me for two separate `ComponentName` field names when I generate the template, as opposed to using the single field, and transforming it as requested. I think the way you're checking for unique field may be factoring in whether it has a transform request which, if my thinking is correct, it shouldn't be.

**Comment by sdinesh86** [comment]
Closed
