### ISSUE TITLE
Settings View: No scroll bar or resize handle

### ISSUE THREAD

**Issue by chorew** [sdinesh86/template-generator#6]
I'm trying to set a template longer than 17 lines and can not see the file content further that line.
To work around i have to edit the content as a normal file then copy/paste.
Thanks!

![screen shot 2016-08-16 at 22 12 30](https://cloud.githubusercontent.com/assets/1790732/17723288/8fc730ec-63fe-11e6-85df-c4ea941ba004.png)

**Comment by sdinesh86** [comment]
Hello @chorew I will look into this and clear it out ASAP
