### ISSUE TITLE
Provide transform functions for template variables

### ISSUE THREAD

**Issue by Aaron-Pool** [sdinesh86/template-generator#7]
First off, just want to say that this plugin is FANTASTIC. Streamlines my development process so much!

The only place I've found (so far) that it doesn't quite meet my needs is when I want insert a particular template variable in camelCase in one place, snake-case in another, and perhaps even PascalCase somewhere else. This is an unfortunately common happenstance in a world where the same labels are used in css, html, and javascript, which have different variable/property naming conventions :(

Is there anyway that functionality could be introduced so that, when using a variable in a template, we could run it through a transform function? For example, if my template variable is ComponentName, and I have the following files:

[{[ComponentName]}].js: 

```
angular
        .module('myModule')
        .component('[{[ComponentName]}]', {
            template: function($templateCache) {
                "ngInject";
                return $templateCache.get('[{[ComponentName]}].tpl.html');
            },
            controller: [{[ComponentName]}]Ctrl,
            bindings: {}
        });
```

[{[ComponentName | snakeCase]}].less:

```
.[{[ComponentName | snakeCase]}] {
}
```

If I created an instance of this template with ComponentName="myCommentList", it would output:

myCommentList.js:

```
angular
        .module('myModule')
        .component('myCommentList', {
            template: function($templateCache) {
                "ngInject";
                return $templateCache.get('myCommentList.tpl.html');
            },
            controller: myCommentListCtrl,
            bindings: {}
        });
```

my-comment-list.less:

```
.my-comment-list {
}
```

**Comment by sdinesh86** [comment]
Hello @Aaron-Pool I am happy that this is proving useful for you.
your suggestion is quite possible and can be done, I am currently tooo occupied with some work and some personal things so I wont be able to give enough time to this.

but if you can start with it I will be able to help you out and give you a hand

let me know if you are intrested

**Comment by Aaron-Pool** [comment]
K! Will definitely think about it. I'm not hugely familiar with coffee script, so that's a bit of a hindrance, but I'll look over it anyways!

**Comment by Aaron-Pool** [comment]
@sdinesh86 Thanks for doing this!
