### ISSUE TITLE
Keybinding Settings Missing

### ISSUE THREAD

**Issue by 3DEsprit** [sdinesh86/template-generator#9]
Since upgrading to 0.13.0, and Atom 1.10.2 on my Xbuntu 16.04 dev system, template generator lost the keybinding option in the Settings. I use custom keybindings, and while the hotkey resolver shows the keys resolving, nothing happens. When turning off the custom hotkeys, the resolver doesn't show the hotkeys registering at all (Ctrl-Shift-J, Alt-N). 

While I don't think this is the issue, here's a snippet from my keymap file just in case:

`'atom-workspace template-generator':
  'ctrl-shift-q': 'toggle-settings-view'
  'alt-n': 'toggle-template-generator'`

I'm uninstalled, and reinstalled to see if anything changed, but nothing. Before I reinstalled today, Alt-N at least worked, and I could choose templates from the drop-down, but now it doesn't even show when pressing Alt-N. 

I want to think this isn't a bug, but I've wiped the package several times, and the outcome is the same, and the Settings never actually have anything to change, just the Templates File variable field, and README.

EDIT: I did find that 'template-generator' was a package in the core options set with 'keybindings disabled', I'm guessing the option was moved, and things work again! Hopefully this will help someone later? :P

**Comment by 3DEsprit** [comment]
Fixed. 

Options moved around I guess. When I upgraded to 1.10 with the keybinds marked as off, it removed this option from the settings. So with keybindings off from settings, it disabled keybindings all together, and showed it disabled in the core settings as "packages with keybindings disabled".

**Comment by sdinesh86** [comment]
@3DEsprit  good you found solution
